---
- name: configure controller
  hosts: localhost
  gather_facts: no

  vars_files:
    - vars.yaml

  tasks:
    - name: Add tower user as a system auditor
      awx.awx.user:
        username: redhat
        password: foobarbaz
        email: redhat@example.org
        auditor: yes
        state: present
        controller_host: "{{ controller_host }}"
        controller_oauthtoken: "{{ controller_token }}"
        #controller_username: "{{ controller_username }}"
        validate_certs: false
