---
- name: configure controller
  hosts: controller01
  gather_facts: no

  vars_files:
    - vars.yaml

  tasks:
    - name: Add tower user as a system auditor
      awx.awx.user:
        username: jdoe
        password: foobarbaz
        email: jdoe@example.org
        auditor: yes
        state: present
        controller_host: "{{ controller_host }}"
        controller_password: "{{ controller_password }}"
        controller_username: "{{ controller_username }}"
        validate_certs: false